Raise required compiler to rust 1.60
Required by expect-test and once_cell.

    error: failed to select a version for the requirement `once_cell = "^1"`
    candidate versions found which didn't match: 1.17.2, 1.17.1, 1.17.0, ...
    location searched: crates.io index
    required by package `expect-test v1.5.0`
        ... which satisfies dependency `expect-test = "^1.4"` (locked to 1.5.0) of package `serde_starlark v0.1.16 (/git/serde-starlark)`